name = "phishy-website"
compatibility_date = "2024-01-01"

compatibility_flags = [
  "nodejs_compat",
  "streams_enable_constructors"
]

# Next.js SSR + Static Files
pages_build_output_dir = ".vercel/output/static"

[build]
command = "npm run build"

[env.production]
name = "phishy-website"

[env.production.vars]
NODE_ENV = "production"
